### ISSUE TITLE
Foreign key other than the first key

### ISSUE THREAD

**Issue by elvispdosreis** [janit/doctrine-inheritance-example#1]
could you help me when the name of the foreign key fields is different from the first key, as would the field mapping

![image](https://user-images.githubusercontent.com/15267623/53285833-68f98e80-3744-11e9-81f1-75d221fa8ec4.png)

**Comment by marcguyer** [comment]
@elvispdosreis Did you find a solution for this? I'm dealing with the same issue - child tables using the FK as the PK.

**Comment by elvispdosreis** [comment]
I could not solve the problem

> @elvispdosreis Did you find a solution for this? I'm dealing with the same issue - child tables using the FK as the PK.
